default_dependencies: false
targets:
  ubuntu-18.04:
    dependencies:
      - libpq5
      - libxml2
      - libxslt1.1
  ubuntu-16.04:
    dependencies:
      - libpq5
      - libxml2
      - libxslt1.1
  debian-10:
    dependencies:
      - libpq5
      - libxml2
      - libxslt1.1
  debian-9:
    dependencies:
      - libpq5
      - libxml2
      - libxslt1.1
  debian-8:
    dependencies:
      - libpq5
      - libxml2
      - libxslt1.1
  centos-7:
    dependencies:
      - libxml2
      - libxslt
      - postgresql-libs
  centos-6:
    dependencies:
      - libxml2
      - libxslt
      - postgresql-libs
  sles-12:
    dependencies:
      - libxml2
      - libxslt
      - postgresql93
